plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
Metrics/AbcSize:
  Max: 28
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/MethodLength:
  Max: 25
Metrics/ModuleLength:
  Max: 250
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Max: 10
Minitest/MultipleAssertions:
  Enabled: false
Naming/FileName:
  Exclude:
    - lib/paystack-gateway.rb
Style/NegatedIf:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
