require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable

Metrics/AbcSize:
  Max: 25
Metrics/MethodLength:
  Max: 25
Minitest/MultipleAssertions:
  Enabled: false
Naming/FileName:
  Exclude:
    - lib/paystack-gateway.rb
Style/NegatedIf:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
